Add UI + refactoring
kkrisstoff/go-server pull request #3
Opened 2018-12-27 16:25 UTC by kkrisstoff

2018-12-28 09:49 UTC, pashura requested changes

2018-12-28 09:49 UTC, pashura commented on main.go
> +	conf, _ := config.GetConfig()
Looks like you return err in GetConfig func, but don't handle err here

2018-12-28 09:49 UTC, pashura commented on main.go
> +	port := fmt.Sprintf(":%s", conf.Port)
Not sure I understand this line. The var name is port but it contain colons and port. Also you use this :9091 in print

2018-12-28 09:49 UTC, pashura commented on config/config.go
> +	var fileName = "config/config.json"
What do you think about making this var as a constant and move it somewhere?

2018-12-28 09:49 UTC, pashura commented on config/config.go
> +		return config, err
I don't fully understand why you return config if the err is not nil?

2018-12-28 09:54 UTC, kkrisstoff commented on main.go
> +	conf, _ := config.GetConfig()
yep. I just don't handle it now

2018-12-28 09:58 UTC, kkrisstoff commented on main.go
> +	port := fmt.Sprintf(":%s", conf.Port)
`Sprintf` formats according to a format specifier and returns the resulting string.
As I see id doesn't print string. It smth like ``:${conf.Port}`` in javascript

2018-12-28 10:02 UTC, kkrisstoff commented on config/config.go
> +		return config, err
I have to return 2 parameters according the function type. In this case `config` is empty structure

2018-12-28 10:03 UTC, kkrisstoff commented on config/config.go
> +	var fileName = "config/config.json"
yep. It makes sense

2019-01-15 18:47 UTC, pashura requested changes

2019-01-15 18:47 UTC, pashura commented on config/config.go
> +func GetConfig() (Config, error) {
Go func names shouldn't start with "Get" etc. There is a reason why in documentation

2019-01-15 18:47 UTC, pashura commented on controllers/add_item.go
> +		fmt.Fprintf(w, "Use POST for adding new item")
Just interesting
Don't use think here should be 'return' ? If the request is not POST it should exit the func.

2019-01-15 18:47 UTC, pashura commented on models/items.go
> +	//fmt.Printf("New item id: %d, message: %v\n", id, message)
It's such a bad practice to have a commented code and to have comment like you have above "//AddItem adds new item to store". This should be described by function name

2019-01-15 18:47 UTC, pashura commented on static/test.txt
> +some text
??

2019-01-15 18:47 UTC, pashura commented on .gitignore
> +ui/out-tsc
there is a .gitignore in ui folder. Don't use think this should be moved to there?

2019-01-15 18:47 UTC, pashura commented on ui/README.md
> +## Development server
There is a scripts in package json
`"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  }`

So I would update UI readme acoording to it.
I mean `npm run start` for `ng serve` etc.

Also I don't see any description of installing dependencies like `npm install` or whatever.
I will be difficult for new user (I mean for me) to run this application

2019-01-15 18:47 UTC, pashura commented on ui/src/app/item-detail/item-detail.component.html
> +      <input [(ngModel)]="item.message" placeholder="Message">
When I click on message it redirects to Title (Web page has title instead of Name)

2019-01-15 18:47 UTC, pashura commented on ui/src/app/item.service.ts
> +  addItem (item: Item): Observable<Item> {
I am not able to add Item

ItemService: addItem failed: Http failure response for (unknown url): 0 Unknown Error

2019-01-15 18:47 UTC, pashura commented on ui/package.json
> +    "test": "ng test",
Test are not worked at all
TOTAL: 7 FAILED, 2 SUCCESS

2019-01-15 18:47 UTC, pashura commented on ui/package.json
> +{
I'm having lots of errors and warnings while I do `nom install`.
Don’t you want to fix installation?
Example of errors:
- CircularJSON is in maintenance only, flatted is its successor (why do you use deprecated module?)
- Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz
- Pre-built binaries not found for fsevents@1.2.4 and node@11.6.0
- ../fsevents.cc:63:6: warning: field 'async_resource' will be initialized after field 'lockStarted' [-Wreorder]


It’s only 4 of them. I would prefer not to have any warnings and errors in new project in 2019 :)

2019-01-16 07:34 UTC, kkrisstoff commented on .gitignore
> +ui/out-tsc
I'll remove .gitignore from UI filder

2019-01-16 07:39 UTC, kkrisstoff commented on controllers/add_item.go
> +		fmt.Fprintf(w, "Use POST for adding new item")
It not necessary in this case. Request can have only one method. But we can add it just to not to recheck method type

2019-01-16 07:42 UTC, kkrisstoff commented on static/test.txt
> +some text
Just for development. I am testing saving data in file

2019-01-16 07:43 UTC, kkrisstoff commented on ui/package.json
> +    "test": "ng test",
We don't have tests now

2019-01-16 08:23 UTC, kkrisstoff commented on ui/src/app/item-detail/item-detail.component.html
> +      <input [(ngModel)]="item.message" placeholder="Message">
yep. We have to change UI

2019-01-16 17:51 UTC, kkrisstoff commented
Merged with tech debt

2019-01-16 17:51 UTC, merged